@host=http://localhost:5198

POST {{host}}/images
Content-Type: multipart/form-data; boundary=FormBoundary
Cookie: 

--FormBoundary
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg

--FormBoundary--