@host=http://localhost:5198

POST {{host}}/api/v1/images
Content-Type: multipart/form-data; boundary=FormBoundary
Cookie:

--FormBoundary
Content-Disposition: form-data; name="imagefile"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg

--FormBoundary--
