// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Petrichor.Modules.Gallery.Infrastructure.Persistence;

#nullable disable

namespace Petrichor.Modules.Gallery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    partial class GalleryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gallery")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImageTag", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ImageId", "TagId")
                        .HasName("pk_image_tags");

                    b.HasIndex("TagId", "ImageId")
                        .HasDatabaseName("ix_image_tags_tag_id_image_id");

                    b.ToTable("image_tags", "gallery");
                });

            modelBuilder.Entity("Petrichor.Modules.Gallery.Domain.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("UploadedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_date_time");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_images_id");

                    b.ToTable("images", "gallery");
                });

            modelBuilder.Entity("Petrichor.Modules.Gallery.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", "gallery");
                });

            modelBuilder.Entity("Petrichor.Shared.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "gallery");
                });

            modelBuilder.Entity("Petrichor.Shared.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "gallery");
                });

            modelBuilder.Entity("Petrichor.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "gallery");
                });

            modelBuilder.Entity("Petrichor.Shared.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "gallery");
                });

            modelBuilder.Entity("ImageTag", b =>
                {
                    b.HasOne("Petrichor.Modules.Gallery.Domain.Images.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_tags_images_image_id");

                    b.HasOne("Petrichor.Modules.Gallery.Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_tags_tags_tag_id");
                });

            modelBuilder.Entity("Petrichor.Modules.Gallery.Domain.Images.Image", b =>
                {
                    b.OwnsOne("Petrichor.Modules.Gallery.Domain.Images.ValueObjects.OriginalImage", "OriginalImage", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("original_image_height");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("original_image_path");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("original_image_width");

                            b1.HasKey("ImageId");

                            b1.ToTable("images", "gallery");

                            b1.WithOwner()
                                .HasForeignKey("ImageId")
                                .HasConstraintName("fk_images_images_id");
                        });

                    b.OwnsOne("Petrichor.Modules.Gallery.Domain.Images.ValueObjects.Thumbnail", "Thumbnail", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("thumbnail_height");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("thumbnail_path");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("thumbnail_width");

                            b1.HasKey("ImageId");

                            b1.ToTable("images", "gallery");

                            b1.WithOwner()
                                .HasForeignKey("ImageId")
                                .HasConstraintName("fk_images_images_id");
                        });

                    b.Navigation("OriginalImage")
                        .IsRequired();

                    b.Navigation("Thumbnail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
