// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Petrichor.Services.Gallery.Common.Persistence;

#nullable disable

namespace Petrichor.Services.Gallery.Common.Persistence.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    [Migration("20251202211720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gallery")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImageTag", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ImageId", "TagId")
                        .HasName("pk_image_tags");

                    b.HasIndex("TagId", "ImageId")
                        .HasDatabaseName("ix_image_tags_tag_id_image_id");

                    b.ToTable("image_tags", "gallery");
                });

            modelBuilder.Entity("Petrichor.Services.Gallery.Common.Domain.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("UploadedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_date_time");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_images_uploader_id");

                    b.ToTable("images", "gallery");
                });

            modelBuilder.Entity("Petrichor.Services.Gallery.Common.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", "gallery");
                });

            modelBuilder.Entity("Petrichor.Services.Gallery.Common.Domain.UserSnapshot", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("pk_user_snapshots");

                    b.HasIndex("UserName")
                        .HasDatabaseName("ix_user_snapshots_user_name");

                    b.ToTable("user_snapshots", "gallery");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "gallery", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "gallery", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ImageTag", b =>
                {
                    b.HasOne("Petrichor.Services.Gallery.Common.Domain.Images.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_tags_images_image_id");

                    b.HasOne("Petrichor.Services.Gallery.Common.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_tags_tags_tag_id");
                });

            modelBuilder.Entity("Petrichor.Services.Gallery.Common.Domain.Images.Image", b =>
                {
                    b.OwnsOne("Petrichor.Services.Gallery.Common.Domain.Images.ValueObjects.OriginalImage", "OriginalImage", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("original_image_height");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("original_image_path");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("original_image_width");

                            b1.HasKey("ImageId");

                            b1.ToTable("images", "gallery");

                            b1.WithOwner()
                                .HasForeignKey("ImageId")
                                .HasConstraintName("fk_images_images_id");
                        });

                    b.OwnsOne("Petrichor.Services.Gallery.Common.Domain.Images.ValueObjects.Thumbnail", "Thumbnail", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("thumbnail_height");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("thumbnail_path");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("thumbnail_width");

                            b1.HasKey("ImageId");

                            b1.ToTable("images", "gallery");

                            b1.WithOwner()
                                .HasForeignKey("ImageId")
                                .HasConstraintName("fk_images_images_id");
                        });

                    b.Navigation("OriginalImage")
                        .IsRequired();

                    b.Navigation("Thumbnail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
